version: "3.7"

services:
  pg_client:
    environment:
      PGDATABASE: ${PGDATABASE}
      PGHOST: postgres
      PGPORT: ${PGPORT}
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
    build:
      context: .
      dockerfile: PgClientDockerfile
    networks:
      - postgres

networks:
  postgres:
    external:
      name: quarkloop_postgres
