version: "3.8"

services:
  # postgres:
  #   image: postgres
  #   restart: unless-stopped
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 5
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DATABASES: spicedb
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data

  spicedb-migrate:
    image: authzed/spicedb
    command: migrate head
    # restart: on-failure
    # depends_on:
    #   - postgres
    environment:
      - "SPICEDB_DATASTORE_ENGINE=postgres"
      - "SPICEDB_DATASTORE_CONN_URI=postgres://postgres:changeme@postgres:5432/TestQuarkloopAuthz?sslmode=disable"
    networks:
      - postgres

  spicedb:
    image: authzed/spicedb
    command: serve-testing
    restart: on-failure
    depends_on:
      - spicedb-migrate
    # healthcheck:
    #   test:
    #     ["CMD", "/usr/local/bin/grpc_health_probe", "-addr", "spicedb:50051"]
    #   interval: 30s
    #   timeout: 3s
    #   retries: 5
    environment:
      - "SPICEDB_DATASTORE_ENGINE=postgres"
      - "SPICEDB_DATASTORE_CONN_URI=postgres://postgres:changeme@postgres:5432/TestQuarkloopAuthz?sslmode=disable"
      - "SPICEDB_GRPC_PRESHARED_KEY=my_passphrase_key"
      - "SPICEDB_HTTP_ENABLED=true"
    ports:
      - "9090:9090"
      - "50051:50051"
      - "8443:8443"
    networks:
      - postgres

networks:
  postgres:
    external:
      name: quarkloop_postgres
